export const TIME_CONSTANTS = {
  MILLISECONDS_PER_SECOND: 1000,
  SECONDS_PER_MINUTE: 60,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  DAYS_PER_WEEK: 7,
  DAYS_PER_TWO_WEEKS: 14,
  DAYS_PER_MONTH: 30,
} as const;

export const MINIMUM_CONCERT_ADVANCE_DAYS = 14;

export const ONE_SECOND_MS = TIME_CONSTANTS.MILLISECONDS_PER_SECOND;
export const ONE_MINUTE_MS = TIME_CONSTANTS.SECONDS_PER_MINUTE * TIME_CONSTANTS.MILLISECONDS_PER_SECOND;
export const FIVE_MINUTES_MS = 5 * ONE_MINUTE_MS;
export const THIRTY_SECONDS_MS = 30 * ONE_SECOND_MS;
export const FIFTY_FIVE_MINUTES_MS = 55 * ONE_MINUTE_MS;
export const ONE_DAY_MS = TIME_CONSTANTS.HOURS_PER_DAY * TIME_CONSTANTS.MINUTES_PER_HOUR * TIME_CONSTANTS.SECONDS_PER_MINUTE * TIME_CONSTANTS.MILLISECONDS_PER_SECOND;
export const ONE_MONTH_MS = TIME_CONSTANTS.DAYS_PER_MONTH * ONE_DAY_MS;

