export const TIME_CONSTANTS = {
  MILLISECONDS_PER_SECOND: 1000,
  SECONDS_PER_MINUTE: 60,
  MINUTES_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  DAYS_PER_WEEK: 7,
  DAYS_PER_TWO_WEEKS: 14,
  DAYS_PER_MONTH: 30,
} as const;

export const MINIMUM_CONCERT_ADVANCE_DAYS = 14;

